CREATE TABLE `exportSchedules` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`organizationId` varchar(64),
	`name` varchar(255) NOT NULL,
	`description` text,
	`frequency` enum('daily','weekly','monthly') NOT NULL,
	`dayOfWeek` int,
	`dayOfMonth` int,
	`hour` int NOT NULL DEFAULT 0,
	`minute` int NOT NULL DEFAULT 0,
	`exportAll` boolean NOT NULL DEFAULT true,
	`promptIds` json,
	`includeVersions` boolean NOT NULL DEFAULT true,
	`includeVariables` boolean NOT NULL DEFAULT true,
	`isActive` boolean NOT NULL DEFAULT true,
	`lastRunAt` timestamp,
	`nextRunAt` timestamp,
	`lastExportUrl` varchar(1000),
	`lastExportError` text,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `exportSchedules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `importExportHistory` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`organizationId` varchar(64),
	`operationType` enum('export','import') NOT NULL,
	`status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`exportUrl` varchar(1000),
	`exportFileName` varchar(255),
	`exportFileSize` int,
	`exportPromptCount` int,
	`exportVersionCount` int,
	`importFileName` varchar(255),
	`importFileSize` int,
	`importedCount` int,
	`skippedCount` int,
	`overwriteExisting` boolean DEFAULT false,
	`importPrefix` varchar(100),
	`errorMessage` text,
	`errorDetails` json,
	`scheduleId` varchar(64),
	`startedAt` timestamp DEFAULT (now()),
	`completedAt` timestamp,
	`expiresAt` timestamp,
	CONSTRAINT `importExportHistory_id` PRIMARY KEY(`id`)
);
