CREATE TABLE `exportTemplates` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`organizationId` varchar(64),
	`name` varchar(255) NOT NULL,
	`description` text,
	`exportAll` boolean NOT NULL DEFAULT true,
	`promptIds` json,
	`includeVersions` boolean NOT NULL DEFAULT true,
	`includeVariables` boolean NOT NULL DEFAULT true,
	`enableCompression` boolean NOT NULL DEFAULT false,
	`frequency` enum('daily','weekly','monthly'),
	`dayOfWeek` int,
	`dayOfMonth` int,
	`hour` int DEFAULT 0,
	`minute` int DEFAULT 0,
	`notifyOnSuccess` boolean NOT NULL DEFAULT true,
	`notifyOnFailure` boolean NOT NULL DEFAULT true,
	`usageCount` int NOT NULL DEFAULT 0,
	`lastUsedAt` timestamp,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `exportTemplates_id` PRIMARY KEY(`id`)
);
