CREATE TABLE `exportAuditLog` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64),
	`organizationId` varchar(64),
	`action` enum('export_created','export_downloaded','export_shared','export_share_accessed','export_share_downloaded','export_deleted','export_encrypted','export_decrypted','import_started','import_completed','import_failed','version_created','version_restored','version_compared','webhook_triggered','schedule_created','schedule_updated','schedule_deleted','schedule_triggered','template_used') NOT NULL,
	`resourceType` enum('export','import','share','version','webhook','schedule','template') NOT NULL,
	`resourceId` varchar(64) NOT NULL,
	`actorType` enum('user','system','anonymous') NOT NULL DEFAULT 'user',
	`actorId` varchar(64),
	`actorName` varchar(255),
	`actorEmail` varchar(255),
	`ipAddress` varchar(45),
	`userAgent` text,
	`requestId` varchar(64),
	`details` json,
	`metadata` json,
	`createdAt` timestamp DEFAULT (now()),
	CONSTRAINT `exportAuditLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `exportAuditSettings` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`organizationId` varchar(64),
	`retentionDays` int NOT NULL DEFAULT 90,
	`logExports` boolean NOT NULL DEFAULT true,
	`logImports` boolean NOT NULL DEFAULT true,
	`logShares` boolean NOT NULL DEFAULT true,
	`logVersions` boolean NOT NULL DEFAULT true,
	`logWebhooks` boolean NOT NULL DEFAULT true,
	`logSchedules` boolean NOT NULL DEFAULT true,
	`logIpAddresses` boolean NOT NULL DEFAULT true,
	`logUserAgents` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `exportAuditSettings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `exportVersions` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`organizationId` varchar(64),
	`versionNumber` int NOT NULL,
	`versionName` varchar(255),
	`description` text,
	`exportHistoryId` varchar(64) NOT NULL,
	`exportUrl` varchar(1000) NOT NULL,
	`exportFileName` varchar(255),
	`exportFileSize` int,
	`promptCount` int NOT NULL DEFAULT 0,
	`versionCount` int NOT NULL DEFAULT 0,
	`promptIds` json,
	`promptSummary` json,
	`isCompressed` boolean DEFAULT false,
	`isEncrypted` boolean DEFAULT false,
	`checksum` varchar(64),
	`tags` json,
	`isArchived` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp DEFAULT (now()),
	`expiresAt` timestamp,
	CONSTRAINT `exportVersions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `exportWebhookDeliveries` (
	`id` varchar(64) NOT NULL,
	`webhookId` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`eventType` enum('export_complete','export_failed','import_complete','import_failed','scheduled_export','share_access') NOT NULL,
	`eventPayload` json,
	`status` enum('pending','success','failed','retrying') NOT NULL DEFAULT 'pending',
	`responseStatus` int,
	`responseBody` text,
	`responseTimeMs` int,
	`attemptCount` int NOT NULL DEFAULT 0,
	`nextRetryAt` timestamp,
	`errorMessage` text,
	`createdAt` timestamp DEFAULT (now()),
	`deliveredAt` timestamp,
	CONSTRAINT `exportWebhookDeliveries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `exportWebhooks` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`organizationId` varchar(64),
	`name` varchar(255) NOT NULL,
	`description` text,
	`url` varchar(1000) NOT NULL,
	`secret` varchar(255),
	`headers` json,
	`triggerOnExportComplete` boolean NOT NULL DEFAULT true,
	`triggerOnExportFailed` boolean NOT NULL DEFAULT true,
	`triggerOnImportComplete` boolean NOT NULL DEFAULT false,
	`triggerOnImportFailed` boolean NOT NULL DEFAULT false,
	`triggerOnScheduledExport` boolean NOT NULL DEFAULT true,
	`triggerOnShareAccess` boolean NOT NULL DEFAULT false,
	`maxRetries` int NOT NULL DEFAULT 3,
	`retryDelaySeconds` int NOT NULL DEFAULT 60,
	`isActive` boolean NOT NULL DEFAULT true,
	`lastTriggeredAt` timestamp,
	`lastSuccessAt` timestamp,
	`lastFailureAt` timestamp,
	`lastErrorMessage` text,
	`totalTriggers` int NOT NULL DEFAULT 0,
	`successCount` int NOT NULL DEFAULT 0,
	`failureCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `exportWebhooks_id` PRIMARY KEY(`id`)
);
