CREATE TABLE `auditAlertHistory` (
	`id` varchar(64) NOT NULL,
	`ruleId` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`organizationId` varchar(64),
	`alertType` varchar(100) NOT NULL,
	`severity` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`title` varchar(255) NOT NULL,
	`message` text NOT NULL,
	`auditEventIds` json NOT NULL,
	`eventCount` int NOT NULL DEFAULT 1,
	`sourceIp` varchar(45),
	`userAgent` text,
	`metadata` json,
	`emailSent` boolean NOT NULL DEFAULT false,
	`webhookSent` boolean NOT NULL DEFAULT false,
	`webhookResponse` text,
	`acknowledged` boolean NOT NULL DEFAULT false,
	`acknowledgedBy` varchar(64),
	`acknowledgedAt` timestamp,
	`acknowledgeNote` text,
	`triggeredAt` timestamp DEFAULT (now()),
	`createdAt` timestamp DEFAULT (now()),
	CONSTRAINT `auditAlertHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `auditAlertRules` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`organizationId` varchar(64),
	`name` varchar(255) NOT NULL,
	`description` text,
	`triggerOnActions` json NOT NULL,
	`triggerOnResourceTypes` json,
	`triggerOnStatus` json,
	`thresholdCount` int NOT NULL DEFAULT 1,
	`thresholdWindowMinutes` int NOT NULL DEFAULT 60,
	`triggerOnUnknownIp` boolean NOT NULL DEFAULT false,
	`allowedIps` json,
	`notifyEmail` boolean NOT NULL DEFAULT true,
	`notifyWebhook` boolean NOT NULL DEFAULT false,
	`webhookUrl` varchar(500),
	`webhookSecret` varchar(255),
	`isActive` boolean NOT NULL DEFAULT true,
	`lastTriggeredAt` timestamp,
	`triggerCount` int NOT NULL DEFAULT 0,
	`cooldownMinutes` int NOT NULL DEFAULT 15,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `auditAlertRules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `versionCleanupHistory` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`organizationId` varchar(64),
	`versionsDeleted` int NOT NULL DEFAULT 0,
	`spaceFreedBytes` int NOT NULL DEFAULT 0,
	`archivedVersions` int NOT NULL DEFAULT 0,
	`criteria` json,
	`status` enum('success','partial','failed') NOT NULL DEFAULT 'success',
	`errorMessage` text,
	`startedAt` timestamp NOT NULL,
	`completedAt` timestamp,
	`createdAt` timestamp DEFAULT (now()),
	CONSTRAINT `versionCleanupHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `versionRetentionSettings` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`organizationId` varchar(64),
	`enabled` boolean NOT NULL DEFAULT false,
	`maxVersionsPerExport` int DEFAULT 10,
	`maxAgeDays` int DEFAULT 90,
	`minVersionsToKeep` int NOT NULL DEFAULT 1,
	`maxTotalSizeMb` int,
	`archiveBeforeDelete` boolean NOT NULL DEFAULT false,
	`archiveLocation` varchar(500),
	`cleanupFrequency` enum('daily','weekly','monthly') NOT NULL DEFAULT 'weekly',
	`lastCleanupAt` timestamp,
	`nextCleanupAt` timestamp,
	`totalVersionsDeleted` int NOT NULL DEFAULT 0,
	`totalSpaceFreedMb` int NOT NULL DEFAULT 0,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `versionRetentionSettings_id` PRIMARY KEY(`id`)
);
