/**
 * PDF Export Utility for Evaluation Reports
 * 
 * Generates professional PDF reports comparing AI provider performance
 */

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface EvaluationExportData {
  evaluationName: string;
  promptName: string;
  createdAt: string;
  results: Array<{
    providerName: string;
    model: string;
    tokensUsed: number;
    latencyMs: number;
    cost: number;
    quality: number;
    output: string;
  }>;
}

export function exportEvaluationToPDF(data: EvaluationExportData) {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(99, 102, 241); // Primary purple-blue color
  doc.text("PromptForge Evaluation Report", 14, 20);
  
  // Evaluation Info
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Evaluation: ${data.evaluationName}`, 14, 35);
  doc.text(`Prompt: ${data.promptName}`, 14, 42);
  doc.text(`Date: ${new Date(data.createdAt).toLocaleDateString()}`, 14, 49);
  
  // Summary Section
  doc.setFontSize(14);
  doc.setTextColor(99, 102, 241);
  doc.text("Performance Summary", 14, 62);
  
  // Calculate summary stats
  const avgTokens = data.results.reduce((sum, r) => sum + r.tokensUsed, 0) / data.results.length;
  const avgLatency = data.results.reduce((sum, r) => sum + r.latencyMs, 0) / data.results.length;
  const totalCost = data.results.reduce((sum, r) => sum + r.cost, 0);
  const avgQuality = data.results.reduce((sum, r) => sum + (r.quality || 0), 0) / data.results.length;
  
  // Best/Worst performers
  const bestCost = data.results.reduce((best, r) => r.cost < best.cost ? r : best);
  const bestSpeed = data.results.reduce((best, r) => r.latencyMs < best.latencyMs ? r : best);
  const bestQuality = data.results.reduce((best, r) => (r.quality || 0) > (best.quality || 0) ? r : best);
  
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(`Average Tokens: ${avgTokens.toFixed(0)}`, 14, 72);
  doc.text(`Average Latency: ${avgLatency.toFixed(0)}ms`, 14, 79);
  doc.text(`Total Cost: $${totalCost.toFixed(4)}`, 14, 86);
  doc.text(`Average Quality: ${avgQuality.toFixed(0)}%`, 14, 93);
  
  doc.text(`Best Cost: ${bestCost.providerName} ($${bestCost.cost.toFixed(4)})`, 14, 103);
  doc.text(`Fastest: ${bestSpeed.providerName} (${bestSpeed.latencyMs}ms)`, 14, 110);
  doc.text(`Highest Quality: ${bestQuality.providerName} (${bestQuality.quality}%)`, 14, 117);
  
  // Detailed Results Table
  doc.setFontSize(14);
  doc.setTextColor(99, 102, 241);
  doc.text("Detailed Results", 14, 132);
  
  autoTable(doc, {
    startY: 138,
    head: [["Provider", "Model", "Tokens", "Latency (ms)", "Cost ($)", "Quality (%)"]],
    body: data.results.map(r => [
      r.providerName,
      r.model,
      r.tokensUsed.toString(),
      r.latencyMs.toString(),
      r.cost.toFixed(4),
      r.quality ? r.quality.toString() : "N/A",
    ]),
    theme: "striped",
    headStyles: {
      fillColor: [99, 102, 241],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 9,
    },
  });
  
  // Output Samples (on new page if needed)
  const finalY = (doc as any).lastAutoTable.finalY || 180;
  
  if (finalY > 240) {
    doc.addPage();
    doc.setFontSize(14);
    doc.setTextColor(99, 102, 241);
    doc.text("Output Samples", 14, 20);
    
    let yPos = 30;
    data.results.forEach((result, index) => {
      if (yPos > 260) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
      doc.setFont("helvetica", "bold");
      doc.text(`${result.providerName} (${result.model})`, 14, yPos);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      const outputLines = doc.splitTextToSize(result.output, 180);
      doc.text(outputLines, 14, yPos + 6);
      
      yPos += 6 + (outputLines.length * 4) + 8;
    });
  } else {
    doc.setFontSize(14);
    doc.setTextColor(99, 102, 241);
    doc.text("Output Samples", 14, finalY + 15);
    
    let yPos = finalY + 25;
    data.results.forEach((result, index) => {
      if (yPos > 260) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
      doc.setFont("helvetica", "bold");
      doc.text(`${result.providerName} (${result.model})`, 14, yPos);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      const outputLines = doc.splitTextToSize(result.output, 180);
      doc.text(outputLines, 14, yPos + 6);
      
      yPos += 6 + (outputLines.length * 4) + 8;
    });
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Generated by PromptForge | Page ${i} of ${pageCount}`,
      14,
      doc.internal.pageSize.height - 10
    );
  }
  
  // Save the PDF
  const fileName = `${data.evaluationName.replace(/[^a-z0-9]/gi, "_")}_${Date.now()}.pdf`;
  doc.save(fileName);
}

export function exportEvaluationToCSV(data: EvaluationExportData) {
  const headers = ["Provider", "Model", "Tokens Used", "Latency (ms)", "Cost ($)", "Quality (%)", "Output"];
  
  const rows = data.results.map(r => [
    r.providerName,
    r.model,
    r.tokensUsed.toString(),
    r.latencyMs.toString(),
    r.cost.toFixed(4),
    r.quality ? r.quality.toString() : "N/A",
    `"${r.output.replace(/"/g, '""')}"`, // Escape quotes in output
  ]);
  
  const csvContent = [
    `# PromptForge Evaluation Report`,
    `# Evaluation: ${data.evaluationName}`,
    `# Prompt: ${data.promptName}`,
    `# Date: ${new Date(data.createdAt).toLocaleDateString()}`,
    "",
    headers.join(","),
    ...rows.map(row => row.join(",")),
  ].join("\n");
  
  // Create download
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  
  link.setAttribute("href", url);
  link.setAttribute("download", `${data.evaluationName.replace(/[^a-z0-9]/gi, "_")}_${Date.now()}.csv`);
  link.style.visibility = "hidden";
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
