import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Generate Postman Collection from OpenAPI Spec
 * Converts the OpenAPI 3.0 spec to Postman Collection v2.1 format
 */

// Read the OpenAPI spec (generated by Swagger)
const openApiSpec = {
  openapi: "3.0.0",
  info: {
    title: "PromptForge API",
    version: "1.0.0",
    description: "REST API for PromptForge - Enterprise prompt engineering platform",
    contact: {
      name: "PromptForge Support",
      url: "https://promptforge.dev",
    },
  },
  servers: [
    {
      url: "https://api.promptforge.dev",
      description: "Production",
    },
    {
      url: "http://localhost:3000",
      description: "Development",
    },
  ],
  components: {
    securitySchemes: {
      BearerAuth: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "API Key",
      },
    },
  },
  security: [{ BearerAuth: [] }],
  paths: {
    "/api/v1/prompts": {
      get: {
        summary: "List all prompts",
        tags: ["Prompts"],
        security: [{ BearerAuth: [] }],
        responses: {
          "200": {
            description: "List of prompts",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    prompts: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          id: { type: "string" },
                          name: { type: "string" },
                          content: { type: "string" },
                          createdAt: { type: "string", format: "date-time" },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    "/api/v1/evaluations": {
      post: {
        summary: "Create evaluation",
        tags: ["Evaluations"],
        security: [{ BearerAuth: [] }],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  promptId: { type: "string" },
                  testCases: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        input: { type: "object" },
                        expectedOutput: { type: "string" },
                      },
                    },
                  },
                },
                required: ["promptId", "testCases"],
              },
            },
          },
        },
        responses: {
          "201": {
            description: "Evaluation created",
          },
        },
      },
    },
    "/api/v1/templates": {
      get: {
        summary: "List marketplace templates",
        tags: ["Templates"],
        security: [{ BearerAuth: [] }],
        responses: {
          "200": {
            description: "List of templates",
          },
        },
      },
    },
  },
};

// Convert to Postman Collection v2.1
const postmanCollection = {
  info: {
    name: "PromptForge API",
    description: openApiSpec.info.description,
    schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
  },
  auth: {
    type: "bearer",
    bearer: [
      {
        key: "token",
        value: "{{API_KEY}}",
        type: "string",
      },
    ],
  },
  variable: [
    {
      key: "BASE_URL",
      value: "http://localhost:3000",
      type: "string",
    },
    {
      key: "API_KEY",
      value: "your_api_key_here",
      type: "string",
    },
  ],
  item: [
    {
      name: "Prompts",
      item: [
        {
          name: "List Prompts",
          request: {
            method: "GET",
            header: [
              {
                key: "Authorization",
                value: "Bearer {{API_KEY}}",
                type: "text",
              },
            ],
            url: {
              raw: "{{BASE_URL}}/api/v1/prompts",
              host: ["{{BASE_URL}}"],
              path: ["api", "v1", "prompts"],
            },
          },
          response: [],
        },
      ],
    },
    {
      name: "Evaluations",
      item: [
        {
          name: "Create Evaluation",
          request: {
            method: "POST",
            header: [
              {
                key: "Authorization",
                value: "Bearer {{API_KEY}}",
                type: "text",
              },
              {
                key: "Content-Type",
                value: "application/json",
                type: "text",
              },
            ],
            body: {
              mode: "raw",
              raw: JSON.stringify(
                {
                  promptId: "prompt_123",
                  testCases: [
                    {
                      input: { variable: "value" },
                      expectedOutput: "Expected result",
                    },
                  ],
                },
                null,
                2
              ),
            },
            url: {
              raw: "{{BASE_URL}}/api/v1/evaluations",
              host: ["{{BASE_URL}}"],
              path: ["api", "v1", "evaluations"],
            },
          },
          response: [],
        },
      ],
    },
    {
      name: "Templates",
      item: [
        {
          name: "List Templates",
          request: {
            method: "GET",
            header: [
              {
                key: "Authorization",
                value: "Bearer {{API_KEY}}",
                type: "text",
              },
            ],
            url: {
              raw: "{{BASE_URL}}/api/v1/templates",
              host: ["{{BASE_URL}}"],
              path: ["api", "v1", "templates"],
            },
          },
          response: [],
        },
      ],
    },
  ],
};

// Create postman directory if it doesn't exist
const postmanDir = path.join(__dirname, "..", "postman");
if (!fs.existsSync(postmanDir)) {
  fs.mkdirSync(postmanDir, { recursive: true });
}

// Write Postman collection to file
const outputPath = path.join(postmanDir, "PromptForge.postman_collection.json");
fs.writeFileSync(outputPath, JSON.stringify(postmanCollection, null, 2));

console.log(`✅ Postman collection generated: ${outputPath}`);
console.log(`\nTo use:`);
console.log(`1. Import the collection into Postman`);
console.log(`2. Set the API_KEY variable to your actual API key`);
console.log(`3. Update BASE_URL if using production`);
